### ISSUE TITLE
Dangerous value for parameter path_width

### ISSUE THREAD

**Issue by Bastrabun** [sbrl/Minetest-WorldEditAdditions#11]
Be careful to execute this command. It brought up the windows error reporting circus on my machine :D No grayscreen, no log entry, just a crash to desktop.

//maze dirt 1 0

**Comment by sbrl** [comment]
Oooh, an infinite loop! Nasty. Thanks for reporting it!

The problem here is that when the maze generator is generating a maze, it moves forwards from a given point by a given number of nodes at a time. Setting it to 0 means that it never moves, and thus never completes generation of the maze :P

In any case this is now fixed. Thanks!
