### ISSUE TITLE
Request: take building material from inventory

### ISSUE THREAD

**Issue by Golutazem** [sbrl/Minetest-WorldEditAdditions#15]
This request is to make it possible to require build operations to take building material from inventory.
Nobody wanted to [do it in WorldEdit](https://github.com/Uberi/Minetest-WorldEdit/issues/138)
, so I make the request here. WorldEditAdditions could become a fork of WorldEdit.

**Comment by sbrl** [comment]
Hey there, @Golutazem! That's a tricky one to answer. Firstly, I haven't actually every played survival, so I'm not really experienced in that area.

Secondly, that would necessitate a major refactor of both WorldEdit and WorldEditAdditions. My goal with WorldEditAdditions is to complement WorldEdit, not replace it :-)

Also, support would have to be added to WorldEdit in order for WorldEditAdditions to implement this feature.

To this end, I'm unfortunately going to have to say that this feature, while a great idea, does not seem likely to be implemented, for the following reasons:

 - The feature needs to be implemented WorldEdit first for me to use it here because of the way the two mods are programmed
 - I'm not willing to make WorldEditAdditions a fork of WorldEdit because:
     - That would require a major refactor of both codebases
     - I would loose the benefits of upstream contributions to WorldEdit having a positive impact on WorldEditAdditions (see #5 for a great example of this)

If, however, the feature is implemented in WorldEdit, please let me know here on GitHub and I'll reopen this issue and do my best to update WorldEditAdditions.

**Comment by sbrl** [comment]
Updated labels to more accurately reflect the situation.
